server:
  port: 9948
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9940/eureka
spring:
  cloud:
    gateway:
      # 允许服务发现
      discovery:
        locator:
          enabled: true
          # 使用小写的服务名，默认是大写
          lower-case-service-id: true
      routes:
        - id: producer
          uri: lb://cloud-producer
          predicates:
            - Path=/hello/**
            - name: RequestRateLimiter
                args:
                  redis-rate-limiter.replenishRate: 1 # 令牌桶每秒填充速率
                  redis-rate-limiter.burstCapacity: 2 # 令牌桶总容量
                  key-resolver: "#{@pathKeyResolver}" # 使用 SpEL 表达式按名称引用 bean
  redis:
    lettuce:
      pool:
        max-wait: 10000
        max-idle: 200
        min-idle: 5
        max-active: 1024
    timeout: 10000
    host: 127.0.0.1
    port: 6379
    database: 5
